services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./storage:/var/www/html/storage
    ports:
      - "8000:80"
    networks:
      - laravel-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"  # Change host port to 3307
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql_data:
